
target 'YHNetSDKDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

platform :ios, '9.0'

pod 'AFNetworking','~> 3.2'

#pod 'AFNetworking','~> 4.0'

end
